import os

new_bank_str = r'''const BANK = [
  { q: "Which theory focuses on the psychological and communication gap between learners and the teacher?", opts: ["E-Learning Theory","Community of Inquiry Theory","Transactional Distance Theory","Connectivism Theory"], ans: 2, exp: "Transactional Distance Theory (Moore, 1973) states that distance is psychological, requiring dialogue to bridge the gap.", hint: "Topic: TDT", sec: "Theories" },
  { q: "According to Community of Inquiry (COI) Theory, meaningful learning requires three presences: Social, Teaching, and...", opts: ["Physical Presence","Cognitive Presence","Technological Presence","Psychological Presence"], ans: 1, exp: "COI posits learning requires Social, Cognitive, and Teaching presences.", hint: "Topic: COI", sec: "Theories" },
  { q: "Which theory is often called the 'learning theory for the digital age'?", opts: ["Andragogy Theory","Connectivism Theory","Constructivism Theory","E-Learning Theory"], ans: 1, exp: "Connectivism (Siemens) argues that knowledge is distributed across networks.", hint: "Topic: Connectivism", sec: "Theories" },
  { q: "The era of learning characterised by paper-based learning delivered through mail is known as:", opts: ["Digital Beginning","Correspondence to Connectivity","Broadcast and Multimedia Expansion","MOOCs"], ans: 1, exp: "The 19th-20th century era used printed materials sent via mail.", hint: "Topic: Paradigm Shift", sec: "Paradigm Shift" },
  { q: "Which distance learning model describes free or low-cost courses offered online to thousands of learners?", opts: ["Blended Learning","Mobile Learning","Massive Open Online Courses (MOOCs)","Virtual University"], ans: 2, exp: "MOOCs democratize education by reaching massive numbers globally.", hint: "Topic: MOOCs", sec: "Models" },
  { q: "What does 'Open Pace' mean in Open and Distance Learning (ODL)?", opts: ["No age restrictions","Free educational materials","Learners progress at their own speed/flexible scheduling","Minimal entry requirements"], ans: 2, exp: "Open Pace encourages self-pace and flexible scheduling.", hint: "Topic: ODL Characteristics", sec: "Open Model" },
  { q: "A traditional university that offers both on-campus and distance programmes is called a:", opts: ["Single-Mode Institution","Virtual University","Dual-Mode Institution","MOOC"], ans: 2, exp: "Dual-Mode Institutions like LASU and Unilag offer both face-to-face and distance learning.", hint: "Topic: Institutional Models", sec: "Open Model" },
  { q: "Which required skill is perhaps the most critical for preventing procrastination in distance learning?", opts: ["Digital Literacy","Self-Regulated Learning (SRL)","Communication Skills","Critical Thinking"], ans: 1, exp: "SRL involves advanced time management and self-motivation to combat procrastination.", hint: "Topic: Required Skills", sec: "Skills" },
  { q: "Which is an example of an Asynchronous Platform?", opts: ["Zoom","Live Webinars","Microsoft Teams","Discussion Forums on Moodle"], ans: 3, exp: "Forums are asynchronous because learners participate at different times.", hint: "Topic: Platforms", sec: "Platforms" },
  { q: "Which of the following is a disadvantage of Synchronous Learning?", opts: ["Delayed feedback","Requires stable internet at a fixed time","Can feel isolating","High schedule flexibility"], ans: 1, exp: "Synchronous learning requires stable internet at a specific, fixed time, reducing flexibility.", hint: "Topic: Sync vs Async", sec: "Platforms" },
  { q: "When designing a program for rural students with limited internet, which strategy reduces the psychological gap according to Transactional Distance Theory?", opts: ["Mandatory 3-hour Zoom sessions","Asynchronous Audio/SMS check-ins","Extensive high-definition video lectures","Virtual Reality simulations"], ans: 1, exp: "Audio/SMS check-ins increase dialogue without requiring high bandwidth.", hint: "Topic: Test Question 1", sec: "Case Study" },
  { q: "In the context of Nigerian distance education, how does the shift to AI-driven personalized learning impact learners?", opts: ["It reduces learner autonomy.","It increases engagement through instant feedback loops.","It entirely replaces the need for human instructors.","It causes absolute disengagement in all scenarios."], ans: 1, exp: "AI-driven platforms adapt to learners, increasing autonomy and engagement via instant feedback.", hint: "Topic: Test Question 2", sec: "Case Study" },
  { q: "Andragogy Theory focuses primarily on:", opts: ["Children's learning","Digital network nodes","Adult learners","Multimedia processing"], ans: 2, exp: "Malcolm Knowles' Andragogy focuses on adult learners who are self-directed.", hint: "Topic: Theories", sec: "Theories" },
  { q: "Which model combines physical classroom instruction with online components?", opts: ["Fully Online Learning Model","Virtual University","Competency-Based Learning","Blended [Hybrid] Learning"], ans: 3, exp: "Blended or Hybrid learning balances face-to-face with digital flexibility.", hint: "Topic: Models", sec: "Models" },
  { q: "According to the notes, what is the completion rate average for MOOCs?", opts: ["50-60%","70-80%","90-100%","5-15%"], ans: 3, exp: "Despite high enrollment numbers, MOOC completion rates tend to be low, averaging 5-15%.", hint: "Topic: MOOCs", sec: "Models" },
  { q: "What does 'distance' refer to in distance education according to its basic definition?", opts: ["Physical separation of teacher and student", "A new method of internet communication", "Only geographical distance measured in kilometres", "The time taken to grade assignments"], ans: 0, exp: "Distance refers to the physical separation for most or all of the instructional process.", hint: "Topic: Definition", sec: "Theories" },
  { q: "Which theory specifically emphasizes that distance is psychological and requires dialogue to bridge the gap?", opts: ["Constructivism Theory", "Connectivism Theory", "Transactional Distance Theory", "Andragogy Theory"], ans: 2, exp: "Moore's theory argues that distance is psychological and communication-based.", hint: "Topic: TDT", sec: "Theories" },
  { q: "Michael Moore is associated with which foundational distance learning theory?", opts: ["E-Learning Theory", "Transactional Distance Theory", "Community of Inquiry Theory", "Connectivism Theory"], ans: 1, exp: "Michael Moore founded the Transactional Distance Theory in 1973.", hint: "Topic: TDT", sec: "Theories" },
  { q: "According to Transactional Distance Theory, the gap increases when there is:", opts: ["More dialogue and less structure", "Less dialogue and more rigid course structure", "No internet connection available", "A lack of adult learners"], ans: 1, exp: "Less dialogue and higher structure increase the transactional distance.", hint: "Topic: TDT", sec: "Theories" },
  { q: "Which theory addresses how digital tools and multimedia facilitate effective online learning?", opts: ["Constructivism Theory", "Community of Inquiry Theory", "Andragogy Theory", "E-Learning Theory"], ans: 3, exp: "E-Learning theory deals with digital tools and multimedia.", hint: "Topic: E-Learning", sec: "Theories" },
  { q: "E-Learning theory draws heavily from which field of science?", opts: ["Quantum Mechanics", "Cognitive Science", "Biology", "Sociology"], ans: 1, exp: "It draws from cognitive science regarding how learners process information.", hint: "Topic: E-Learning", sec: "Theories" },
  { q: "According to E-Learning Theory, learners process information better when:", opts: ["It is only in text format", "Visuals and audio are well-coordinated", "There are no multimedia elements", "It is delivered entirely through mobile phones"], ans: 1, exp: "Information is processed better when visuals and audio are well-coordinated.", hint: "Topic: E-Learning", sec: "Theories" },
  { q: "Who are the developers of the Community of Inquiry (COI) Theory?", opts: ["Michael Moore", "Ruth Clark and Richard Mayer", "Garrison, Anderson & Archer", "George Siemens"], ans: 2, exp: "COI was developed by Garrison, Anderson & Archer.", hint: "Topic: COI", sec: "Theories" },
  { q: "Which presence in the Community of Inquiry Theory involves critical thinking and problem-solving?", opts: ["Teaching Presence", "Cognitive Presence", "Social Presence", "Physical Presence"], ans: 1, exp: "Cognitive presence deals with critical thinking and problem-solving.", hint: "Topic: COI", sec: "Theories" },
  { q: "Which theory argues that knowledge is distributed across networks?", opts: ["Andragogy Theory", "Connectivism Theory", "E-Learning Theory", "Transactional Distance Theory"], ans: 1, exp: "Connectivism argues knowledge is distributed across networks.", hint: "Topic: Connectivism", sec: "Theories" },
  { q: "Malcolm Knowles is best known for which theory focusing on adult learners?", opts: ["Constructivism Theory", "Community of Inquiry Theory", "Andragogy Theory", "Connectivism Theory"], ans: 2, exp: "Andragogy focuses on adult learners, developed by Malcolm Knowles.", hint: "Topic: Andragogy", sec: "Theories" },
  { q: "Which theory holds that learners actively build their own understanding from experiences?", opts: ["Constructivism Theory", "Andragogy Theory", "Connectivism Theory", "E-Learning Theory"], ans: 0, exp: "Constructivism states that learners construct their own understanding.", hint: "Topic: Constructivism", sec: "Theories" },
  { q: "During the 19th-20th century, distance learning was primarily delivered through:", opts: ["Radio broadcast", "Paper-based correspondence", "Emails", "Learning Management Systems"], ans: 1, exp: "It was the era of correspondence to connectivity.", hint: "Topic: Paradigm", sec: "Paradigm Shift" },
  { q: "Which technology was characteristic of the 'Broadcast and Multimedia Expansion' era?", opts: ["Radio and television", "Floppy disks and CDs", "Internet forums", "Mobile apps"], ans: 0, exp: "Mid-20th century saw the use of radio and TV.", hint: "Topic: Paradigm", sec: "Paradigm Shift" },
  { q: "The 'Digital Beginning' era in the 1980s-1990s was characterized by learning using:", opts: ["Radio", "Mail correspondence", "Offline computers with CDs and floppy disks", "Live Zoom sessions"], ans: 2, exp: "Digital Beginning used computers, CDs and floppy disks.", hint: "Topic: Paradigm", sec: "Paradigm Shift" },
  { q: "Which platforms emerged during the 'Internet and Online Learning' era?", opts: ["Television networks", "Learning Management Systems (LMS) like Moodle", "Virtual Reality", "Radio broadcasts"], ans: 1, exp: "LMS platforms emerged during the Internet era.", hint: "Topic: Paradigm", sec: "Paradigm Shift" },
  { q: "What does MOOC stand for?", opts: ["Massive Online Operational Course", "Mainstream Open Online Classes", "Massive Open Online Courses", "Multiple Offline Organized Courses"], ans: 2, exp: "MOOCs allow thousands of learners to access courses globally.", hint: "Topic: Paradigm", sec: "Paradigm Shift" },
  { q: "The current paradigm of distance learning relies heavily on:", opts: ["Radio and TV", "Paper and mail", "AI-driven platforms and Hybrid learning", "CD-ROMs"], ans: 2, exp: "Current paradigm includes AI-driven and Hybrid learning.", hint: "Topic: Paradigm", sec: "Paradigm Shift" },
  { q: "How do AI platforms personalize learning experiences today?", opts: ["By adapting content to a learner's pace and performance", "By completely removing the need for a curriculum", "By replacing all human contact", "By enforcing a rigid course structure"], ans: 0, exp: "AI adapts content to a learner's pace and performance.", hint: "Topic: Paradigm", sec: "Paradigm Shift" },
  { q: "A model delivered entirely via the internet using platforms like Canvas or Blackboard is called:", opts: ["Blended Learning", "Fully Online Learning Model", "Virtual University", "Competency-Based Learning"], ans: 1, exp: "Fully Online Learning Model is delivered entirely via the internet.", hint: "Topic: Models", sec: "Models" },
  { q: "What is a major disadvantage of the Fully Online Learning Model?", opts: ["It is not scalable", "It requires strong digital literacy and reliable internet", "It offers no flexibility", "It is extremely expensive compared to traditional schooling"], ans: 1, exp: "It heavily depends on technology infrastructure and digital literacy.", hint: "Topic: Models", sec: "Models" },
  { q: "Which model is described as increasingly popular post-COVID-19?", opts: ["Mobile Learning", "Blended [Hybrid] Learning", "Competency-Based Learning", "Virtual University"], ans: 1, exp: "Blended Learning combines physical and online learning.", hint: "Topic: Models", sec: "Models" },
  { q: "A major advantage of Mobile Learning (M-Learning) is:", opts: ["It provides a large screen for viewing complex diagrams", "It completely eliminates data costs", "It is highly accessible, especially in regions with limited infrastructure", "It forces students to attend physical classes"], ans: 2, exp: "M-Learning is highly accessible, even with limited infrastructure.", hint: "Topic: Models", sec: "Models" },
  { q: "In which model do students progress by demonstrating mastery of skills rather than completing a fixed time period?", opts: ["Virtual University", "Competency-Based Learning", "Fully Online Learning Model", "MOOCs"], ans: 1, exp: "Competency-Based Learning focuses on mastery of skills.", hint: "Topic: Models", sec: "Models" },
  { q: "What is the typical completion rate for Massive Open Online Courses (MOOCs) despite their high enrolment?", opts: ["90-100%", "50-70%", "5-15%", "30-40%"], ans: 2, exp: "MOOCs have high dropout rates, with completion around 5-15%.", hint: "Topic: Models", sec: "Models" },
  { q: "A fully online institution that exists entirely online and offers full degree certification is called a:", opts: ["MOOC", "Dual-Mode Institution", "Virtual University", "Blended Learning Center"], ans: 2, exp: "Virtual Universities offer full degree certification entirely online.", hint: "Topic: Models", sec: "Models" },
  { q: "What does ODL stand for?", opts: ["Online Distance Logic", "Open and Distance Learning", "Offline and Digital Learning", "Organized Distance Learning"], ans: 1, exp: "ODL stands for Open and Distance Learning.", hint: 'Topic: Open Model', sec: "Open Model" },
  { q: "Which characteristic of the Open Model means there are minimal entry requirements?", opts: ["Open Access", "Open Pace", "Open Admission", "Open Content"], ans: 2, exp: "Open Admission minimizes entry barriers and accepts prior learning.", hint: 'Topic: Open Model', sec: "Open Model" },
  { q: "Which characteristic of ODL encourages flexible scheduling?", opts: ["Open Admission", "Open Content", "Open Pace", "Open Access"], ans: 2, exp: "Open Pace allows learners to progress at their own speed.", hint: 'Topic: Open Model', sec: "Open Model" },
  { q: "OER stands for:", opts: ["Online Educational Registration", "Open Educational Resources", "Offline Electronic Resources", "Open Evaluation Rules"], ans: 1, exp: "OER refers to reusable materials under open licenses.", hint: 'Topic: Open Model', sec: "Open Model" },
  { q: "An institution dedicated solely to distance education is known as a:", opts: ["Dual-Mode Institution", "Single-Mode Institution", "Virtual University", "Blended Institution"], ans: 1, exp: "Single-Mode Institutions are dedicated entirely to distance education.", hint: 'Topic: Open Model', sec: "Open Model" },
  { q: "NOUN (National Open University of Nigeria) is an example of a:", opts: ["Dual-Mode Institution", "Single-Mode Institution", "Traditional University", "Competency-Based Center"], ans: 1, exp: "NOUN is a Single-Mode Institution.", hint: 'Topic: Open Model', sec: "Open Model" },
  { q: "LASU and Unilag offering both on-campus and distance programmes makes them:", opts: ["Single-Mode Institutions", "Dual-Mode Institutions", "Virtual Universities", "MOOCs"], ans: 1, exp: "Institutions offering both are Dual-Mode Institutions.", hint: 'Topic: Open Model', sec: "Open Model" },
  { q: "Which of the following is a disadvantage of ODL?", opts: ["It democratises higher education", "It supports lifelong learning", "High dropout rate and digital divide", "It is cost-effective"], ans: 2, exp: "High dropout rates and digital divide are major disadvantages.", hint: 'Topic: Open Model', sec: "Open Model" },
  { q: "SRL stands for:", opts: ["Student Registration List", "Self-Regulated Learning", "Synchronous Resource Learning", "Systematic Research Logic"], ans: 1, exp: "SRL includes time management and self-motivation.", hint: "Topic: Skills", sec: "Skills" },
  { q: "Mastery of LMS platforms and critical evaluation of resources fall under which skill?", opts: ["Self-Regulated Learning", "Digital and Information Literacy", "Communication & Collaboration", "Critical Thinking"], ans: 1, exp: "This refers to Digital and Information Literacy.", hint: "Topic: Skills", sec: "Skills" },
  { q: "The ability to analyze complex material without immediate lecturer support is an example of:", opts: ["Lifelong Learning", "Digital Literacy", "Critical Thinking & Problem Solving", "Self-Regulated Learning"], ans: 2, exp: "Critical Thinking helps analyze materials independently.", hint: "Topic: Skills", sec: "Skills" },
  { q: "Building a Personal Learning Network (PLN) is associated with which skill?", opts: ["Lifelong Learning & Adaptability", "Digital Literacy", "Communication Skills", "Critical Thinking"], ans: 0, exp: "It falls under Lifelong Learning & Adaptability.", hint: "Topic: Skills", sec: "Skills" },
  { q: "Google Meet and Microsoft Teams are examples of:", opts: ["Asynchronous Platforms", "Synchronous Platforms", "Paper-based correspondence", "MOOCs"], ans: 1, exp: "These are live, real-time synchronous platforms.", hint: "Topic: Platforms", sec: "Platforms" },
  { q: "Which of the following is an advantage of Synchronous Learning?", opts: ["Does not require internet", "Immediate interaction reduces transactional distance", "Compatible with Open Pace", "Can be done completely offline"], ans: 1, exp: "It reduces transactional distance and builds Social Presence.", hint: "Topic: Platforms", sec: "Platforms" },
  { q: "WhatsApp Groups, Pre-recorded Lectures, and Podcasts are examples of:", opts: ["Synchronous Learning", "Asynchronous Learning", "Virtual Reality", "Blended Learning"], ans: 1, exp: "These do not happen in real-time.", hint: "Topic: Platforms", sec: "Platforms" },
  { q: "Which type of learning is more compatible with 'Open Pace'?", opts: ["Synchronous Learning", "Asynchronous Learning", "Live Webinars", "Traditional Classroom"], ans: 1, exp: "Asynchronous learning allows learners to study at their own pace.", hint: "Topic: Platforms", sec: "Platforms" },
  { q: "A disadvantage of Asynchronous Learning is:", opts: ["It is not flexible", "It does not support mobile devices", "Delayed feedback can increase transactional distance", "It requires stable internet at a fixed time"], ans: 2, exp: "Delayed feedback increases the psychological gap.", hint: "Topic: Platforms", sec: "Platforms" },
  { q: "The notes conclude that the best solution for distance learning is:", opts: ["Fully Synchronous Learning", "Fully Asynchronous Learning", "Hybrid/Blended Learning", "Paper-based correspondence"], ans: 2, exp: "Hybrid/Blended learning offers a flexible, student-centered experience.", hint: "Topic: Platforms", sec: "Platforms" },
  { q: "If a student prefers to study late at night by watching recorded videos, they are engaging in:", opts: ["Synchronous Learning", "Asynchronous Learning", "Blended Learning", "Traditional Learning"], ans: 1, exp: "Recorded videos accessed at one's own time are asynchronous.", hint: "Topic: Platforms", sec: "Platforms" }
]'''

with open('create_edt304.py', 'r', encoding='utf-8') as f:
    content = f.read()

# Replace the BANK array inside new_bank
bank_block_start = content.find("new_bank = '''const BANK = [")
if bank_block_start != -1:
    bank_block_end = content.find("'''", bank_block_start + 15)
    content = content[:bank_block_start] + "new_bank = '''" + new_bank_str + "\n'''" + content[bank_block_end + 3:]

# Add the JS fixes before writing
js_fix_code = '''
    quiz_html = quiz_html.replace(
        "if (diff === 'obj1') filtered = BANK.filter(q => q.sec === 'Definitions');",
        "if (diff === 'obj1') filtered = BANK.filter(q => ['Theories', 'Paradigm Shift', 'Case Study'].includes(q.sec));"
    )
    quiz_html = quiz_html.replace(
        "else if (diff === 'obj2') filtered = BANK.filter(q => q.sec === 'Entrepreneurship');",
        "else if (diff === 'obj2') filtered = BANK.filter(q => ['Models', 'Open Model'].includes(q.sec));"
    )
    quiz_html = quiz_html.replace(
        "else if (diff === 'obj3') filtered = BANK.filter(q => q.sec === 'Finance & HRM');",
        "else if (diff === 'obj3') filtered = BANK.filter(q => ['Skills', 'Platforms'].includes(q.sec));"
    )
    # Ensure it says 60 questions
    quiz_html = quiz_html.replace('CBT practice quiz · 15 questions · Timed', 'CBT practice quiz · 60 questions · Timed')
'''

insert_pos = content.find('quiz_html = quiz_html[:bank_code_start]')
if insert_pos != -1:
    content = content[:insert_pos] + js_fix_code + content[insert_pos:]

# Remove the old buggy replace
content = content.replace("quiz_html = quiz_html.replace('CBT practice quiz · 60 questions · Timed', 'CBT practice quiz · 15 questions · Timed')", "")

with open('create_edt304.py', 'w', encoding='utf-8') as f:
    f.write(content)

print("Patch applied to create_edt304.py")
